[package]
name = "rust-image-viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Add local image-lib dependency
image-lib = { path = "../image-lib" }
rayon = "1.8.0"
