name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Exe
      run: cargo build --manifest-path ./rust-image-viewer/Cargo.toml --verbose
    - name: Build Lib
      run: cargo build --manifest-path ./image-lib/Cargo.toml --verbose
    - name: Run tests
      run: cargo test --manifest-path ./image-lib/Cargo.toml --verbose
